package com.gainsay;

/**
 * Driver class generated by Maven
 *
 */
public class App 
{
    public static void main(String[] args) {
        System.out.println("Welcome to Parallax!");
    }
}
